CholitoProject/CholitoProject/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf.urls.static import static
from CholitoProject import settings
from CholitoProject.views import AuthView, LogOutView

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^complaint/', include('complaint.urls')),
    url(r'^auth/', AuthView.as_view(), name='auth'),
    url(r'^logout/', LogOutView.as_view(), name='logout'),
    url(r'^municipality/', include('municipality.urls')),
    url(r'^animal/', include('animals.urls')),
    url(r'^ong/', include('ong.urls')),
    url(r'', include('naturalUser.urls')),
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

CholitoProject/complaint/urls.py
from django.conf.urls import url

from .views import *

urlpatterns = [
    url(r'^$', ComplaintView.as_view(), name='complaint-form'),
    url(r'^send', ComplaintSendView.as_view(), name='make-complaint'),
    url(r'^(?P<pk>\d+)/$', ComplaintRenderView.as_view(), name='see-complaint'),
    url(r'^act/(?P<pk>\d+)/$', ComplaintActState.as_view(), name='act-complaint'),
]

CholitoProject/ong/urls.py
from django.conf.urls import url

from ong.views import *
app_name = 'ong'

urlpatterns = [
    url(r'^(?P<pk>\d+)/$', ONGforNaturalUser.as_view(), name='ong-logged'),
]

CholitoProject/complaint/models.py
from django.db import models
from django.utils import timezone

from municipality.models import Municipality


class AnimalType(models.Model):
    name = models.TextField(max_length=100)

    def __str__(self):
        return self.name


class Complaint(models.Model):
    COMPLAINT_OPTIONS = (
        (1, "Abandono en la calle"),
        (2, "Exposición a temperaturas extremas"),
        (3, "Falta de agua"),
        (4, "Falta de comida"),
        (5, "Violencia"),
        (6, "Venta ambulante"),
    )

    COMPLAINT_STATUS = (
        (1, "Reportada"),
        (2, "Consolidada"),
        (3, "Verificada"),
        (4, "Cerrada"),
        (5, "Desechada"),
    )

    GENDER_OPTIONS = (
        (1, "Macho"),
        (2, "Hembra"),
    )

    WOUND_OPTIONS = (
        (True, "Sí"),
        (False, "No"),
    )

    description = models.TextField(max_length=1000)
    case = models.SmallIntegerField(choices=COMPLAINT_OPTIONS)
    lat = models.DecimalField(max_digits=9, decimal_places=6, null=True)
    lng = models.DecimalField(max_digits=9, decimal_places=6, null=True)
    directions = models.TextField(max_length=200, null=True)
    status = models.SmallIntegerField(choices=COMPLAINT_STATUS)
    animal_type = models.ForeignKey(AnimalType)
    gender = models.SmallIntegerField(choices=GENDER_OPTIONS)
    wounded = models.BooleanField(choices=WOUND_OPTIONS)
    color = models.TextField(max_length=50)
    municipality = models.ForeignKey(Municipality)
    date = models.DateTimeField(default=timezone.now)#auto_now_add=True)

    def __str__(self):
        return "Complaint #" + str(self.pk) + " (" + str(self.municipality.name) + ")"


class ComplaintImage(models.Model):
    image = models.ImageField(upload_to='complaints/')
    complaint = models.ForeignKey('Complaint', on_delete=models.CASCADE)

    def __str__(self):
        return "Complaint Image from #" + str(self.complaint.pk)

CholitoProject/complaint/forms.py
from django import forms

from .models import Complaint, AnimalType


class ComplaintForm(forms.ModelForm):
    class Meta:
        model = Complaint
        fields = (
            'case',
            'animal_type',
            'gender',
            'color',
            'wounded',
            'directions',
            'lat',
            'lng',
            'description',
            'municipality',
        )
        widgets = {
            'case': forms.Select(attrs={'id': 'case-input'}),
            'animal_type': forms.Select(attrs={'id': 'animal_type-input'}),
            'color': forms.TextInput(attrs={'id': 'color-input'}),
            'gender': forms.RadioSelect(attrs={'id': "gender-input"}),
            'wounded': forms.RadioSelect(attrs={'id': "wounded-input"}),
            'lat': forms.HiddenInput(),
            'lng': forms.HiddenInput(),
            'directions': forms.HiddenInput(),
            'description': forms.TextInput(attrs={'id': 'description-input'}),
            'municipality': forms.Select(attrs={'id': 'municipality-input'}),
        }

    def __init__(self, *args, **kwargs):
        super(ComplaintForm, self).__init__(*args, **kwargs)
        self.fields['animal_type'] = forms.ModelChoiceField(queryset=AnimalType.objects)


class ImageForm(forms.Form):
    complaint_image = forms.ImageField(
        widget=forms.FileInput(
            attrs={'id': 'image-input', 'class': "form-control", 'placeholder': "Agrega una imagen de tu denuncia"}))

CholitoProject/complaint/views.py
from django.contrib.auth.mixins import PermissionRequiredMixin, LoginRequiredMixin
from django.shortcuts import render, redirect, get_object_or_404
from django.views import View

from CholitoProject.userManager import get_user_index
from complaint.forms import ComplaintForm, ImageForm
from complaint.models import Complaint, ComplaintImage, AnimalType


class ComplaintView(View):
    form = ComplaintForm(
        initial={'lat': 20, 'lng': 20, 'directions': "beauchef"}, prefix='complaint')
    image_form = ImageForm(prefix='image')
    animals = AnimalType.objects.all()
    context = {'form': form, 'image_form': image_form, 'animals': animals}
    template_name = 'complaint.html'

    def get(self, request, **kwargs):
        user = get_user_index(request.user)
        self.context['c_user'] = user
        self.context['animal_types'] = self.animals
        return render(request, self.template_name, context=self.context)


class ComplaintSendView(View):

    def post(self, request, **kwargs):
        form = ComplaintForm(request.POST, prefix='complaint')
        image_form = ImageForm(request.POST, request.FILES, prefix='image')
        if form.is_valid():
            complaint = form.save(commit=False)
            complaint.status = 1
            complaint.save()
            if image_form.is_valid():
                ComplaintImage.objects.create(
                    complaint=complaint, image=image_form.cleaned_data.get('complaint_image'))

        return redirect('/')


class ComplaintRenderView(PermissionRequiredMixin, LoginRequiredMixin, View):
    template_name = 'view_complaint.html'
    permission_required = 'municipality.municipality_user_access'
    context = {}

    def get(self, request, pk, **kwargs):
        user = get_user_index(request.user)
        self.context['c_user'] = user
        complaint = get_object_or_404(Complaint, pk=pk)
        self.context['complaint'] = complaint

        images = ComplaintImage.objects.filter(complaint=complaint)
        self.context['images'] = images
        animals = AnimalType.objects.all()
        self.context['animal_types'] = animals

        return render(request, self.template_name, context=self.context)


class ComplaintActState(PermissionRequiredMixin, LoginRequiredMixin, View):
    template_name = 'view_complaint.html'
    permission_required = 'municipality.municipality_user_access'
    context = {}

    def post(self, request, pk, **kwargs):
        complaint = get_object_or_404(Complaint, pk=pk)
        complaint.status = request.POST['status']
        complaint.save()

        animals = AnimalType.objects.all()
        self.context['animal_types'] = animals
        self.context['complaint'] = complaint

        images = ComplaintImage.objects.filter(complaint=complaint)
        self.context['images'] = images
        # render(request, self.template_name, context=self.context)
        return redirect('see-complaint', pk=pk)

CholitoProject/complaint/templates/complaint.html
{% extends "User/user-standard.html" %}

{% block title %}Denuncia{% endblock %}

{% block content-header %}Subir Denuncia{% endblock %}

{% block content %}
    <form method="POST" enctype="multipart/form-data" action="{% url 'make-complaint' %}">

        {% csrf_token %}
        <div class="form-group">
            <label class="control-label col-sm-10" for="case-input">Tipo de maltrato:</label>
            <div class="col-sm-10">
                {{ form.case }}
            </div>
        </div>
        <div class="form-group">
            <label class="control-label col-sm-10" for="animal_type-input">Tipo de animal</label>
            <div class="col-sm-10">
                {{ form.animal_type }}
            </div>
        </div>
        <div class="form-check form-check-inline">
            <label class="control-label col-sm-10" for="gender-input">Sexo:</label>
            <div class="col-sm-10">
                {{ form.gender }}
            </div>
        </div>
        <div class="form-group">
            <label class="control-label col-sm-10" for="color-input">Color:</label>
            <div class="col-sm-10">
                {{ form.color }}
            </div>
        </div>
        <div class="form-group">
            <label class="control-label col-sm-10" for="wounded-input">Herido:</label>
            <div class="col-sm-10">
                {{ form.wounded }}
            </div>
        </div>
        <div class="form-group">
            <label class="control-label col-sm-10" for="municipality-input">Municipalidad:</label>
            <div class="col-sm-10">
                {{ form.municipality }}
            </div>
        </div>
        <div class="form-group">
            <label class="control-label col-sm-10" for="wounded-input">Comentario:</label>
            <div class="col-sm-10">
                {{ form.description }}
            </div>
        </div>

        <div class="form-group">
            <label class="control-label col-sm-10" for="image-input">Foto del animal:</label>
            <div class="col-sm-10">
                {{ image_form.complaint_image }}
            </div>
        </div>

        {{ form.directions }}
        {{ form.lat }}
        {{ form.lng }}

        <div class="form-group">
            <div class="col-sm-10">
                <br>

                <input type="submit" class="btn btn-primary" value="Envia denuncia"/>
                <input type="button" class="btn btn-default" value="Cancelar"/>
            </div>
        </div>

    </form>

{% endblock %}

CholitoProject/complaint/templates/view_complaint.html
{% extends "Municipality/municipality-standard.html" %}
{% load static %}

{% block title %}Denuncia #{{ complaint.pk }}{% endblock %}

{% block content %}
    <h2 align="center">Denuncia #{{ complaint.pk }}</h2>
    <table class="table table-responsive">
        <tr>
            <th>Tipo de Denuncia:</th>
            <td>{{ complaint.get_case_display }}</td>
            <th>Tipo de Animal:</th>
            <td> {{ complaint.animal_type }}</td>
            <th>Color:</th>
            <td>{{ complaint.color }}</td>
        </tr>
        <tr>
            <th>Direccion:</th>
            <td>{{ complaint.directions }}</td>
            <th>Sexo:</th>
            <td>{{ complaint.get_gender_display }}</td>
            <th>¿Herido?:</th>
            <td>{{ complaint.get_wounded_display }}</td>
        </tr>
        <tr>
            <th>Comentario:</th>
            <td colspan="5">{{ complaint.description }}</td>
        </tr>
    </table>
    {% if images %}
        <!-- slider -->
        <div class="row">
            <div class="col-md-9" id="slider">
                <!-- Top part of the slider -->
                <div class="row">
                    <div class="col-md-3" id="carousel-bounding-box">
                        <div id="myCarousel" class="carousel slide">
                            <!-- Carousel items -->
                            <div class="carousel-inner">

                                {% for image in images %}

                                    <div class="item"
                                            {% if forloop.counter0 == 0 %}
                                         id="slide0"
                                            {% endif %}
                                         data-slide-number="{{ forloop.counter0 }}">
                                        <img class="img-rounded img-responsive" src="{{ image.image.url }}">
                                    </div>

                                {% endfor %}

                            </div><!--/carousel-inner-->
                        </div><!--/carousel-->
                        <ul class="carousel-controls-mini list-inline text-center">
                            <li><a href="#myCarousel" data-slide="prev">‹</a></li>
                            <li><a href="#myCarousel" data-slide="next">›</a></li>
                        </ul><!--/carousel-controls-->
                    </div><!--/col-->
                    <div class="col-md-4" id="carousel-text"></div>

                </div><!--/row-->
            </div><!--/col-->
        </div><!--/row slider-->


        <script>
            $(document).ready(function () {
                jQuery("#slide0").addClass("active");
            });
        </script>

    {% endif %}

    <div class="text-center">
        <h3>Estado: <font color="#428bca"> {{ complaint.get_status_display }}</font></h3>

        <form method="POST" enctype="multipart/form-data" action="{% url 'act-complaint' complaint.pk %}">
            {% csrf_token %}

            <input type="hidden" name="id-complaint" id="id-complaint" value="{{ complaint.pk }}"/>
            <select class="btn btn-default btn-lg" id="status" name="status">
                <option value="1">Reportada</option>
                <option value="2">Consolidada</option>
                <option value="3">Verificada</option>
                <option value="4">Cerrada</option>
                <option value="5">Desechada</option>
            </select>

            <button type="submit" class="btn btn-primary btn-lg">Actualizar Estado</button>
        </form>


    </div>



{% endblock %}